# Generated by Django 5.2.1 on 2025-06-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_reseller_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("direct", "Direct User"), ("reseller", "Reseller User")],
                default="direct",
                max_length=20,
            ),
        ),
    ]
