# Generated by Django 5.2.1 on 2025-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Customer"),
                    ("reseller", "Reseller Customer"),
                ],
                default="direct",
                max_length=20,
            ),
        ),
    ]
